config/routes.rb
SampleApp::Application.routes.draw do
  resources :invitations
  resources :password_resets
  resources :default_policies

  resources :meta do 
    resources :resources
  end

  resources :resources

  resources :phases

  resources :policies

  resources :events
  match '/generate_stream'=>'meta#generate_stream'
  match '/generate_structure'=>'meta#generate_structure'
  match '/generate_scenario'=>'meta#generate_scenario'
  match '/generate_space'=>'meta#generate_space'
  match '/generate_society'=>'meta#generate_society'
  match '/rake_tasks'=>'tasks#rake_tasks'
  match '/rake_phases'=>'phases#rake_phases'
  match '/rake_users'=>'users#rake_users'
  match "phases/savesort" => 'phases#savesort'
  match "shippings_logs/recent"=> 'shipping_logs#recent'
  match '/articles(/:year(/:month))' => 'articles#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'events#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/tasks/calendar(/:year(/:month))' => 'tasks#view_calendar', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  match '/tasks/rake_tasks', :to => 'tasks#rake_tasks'
  
  resources :tasks do 
    resources :resources
  end
  get "sessions/new"

  resources :users 
    match '/users/:id/' => 'users#update', :format =>:json, :via => :put
  resources :sessions, :only => [:new,:create,:destroy]
  
  match "/projects/withdraw", :controller => 'projects', :action => 'withdraw'
   match "/defaultphases/:id", :to=>'defaultphases#show'
   match "/soc_del", :to=>'meta#soc_del'
   match "/struc_del", :to=>'meta#struc_del'
  
  match "/tasks/index.js", :controller => 'tasks', :action => 'index', :format => :js
  get "users/new"
  match "/phases/make", :to=>'phases#make', :via => :post

  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signup/:invitation_token', :to=>'users#new'
  match '/signin', :to => 'pages#home'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  
  resources :projects do 
    resources :resources
  end
  

  match '/projects/new_user', :to=>'projects#new_user'
  match '/users/remove', :to=>'users#remove'

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  has_many :memberships
  has_many :projects, :through => :memberships
  has_many :sent_invitations, :class_name => 'Invitation', :foreign_key => 'sender_id'
  belongs_to :invitation
  
  accepts_nested_attributes_for :memberships,:allow_destroy=>true
  
  attr_accessor :project_user,:password,:password_confirmation
  
  attr_accessible :id,:name, :user_attributes, :email,:designations_attributes,:memberships_attributes,:homepage, :contact,:password,:password_confirmation, :invitation_token,:invitation_attributes

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :presence => true,
                  :length => {:maximum => 50}
  #validates :role, :presence => true,
   #               :length => {:maximum => 50},
    #              :if=>:should_not_validate_user
  validates :email, :presence =>true,
                  :format => {:with => email_regex},
                 :uniqueness => {:case_sensitive => false},
                :on => :create
                
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 },
                      :if => :should_validate_user,
                      :on=>:create
                      
   validates :password_confirmation, :presence=>true,:on=>:create,:if=>:should_validate_user
   validates_confirmation_of :password,:on=>:create,:if=>:should_validate_user
                       
   before_save :encrypt_password, :on=>:create,:if => :should_validate_user
  
  
  def invitation_token
    invitation.token if invitation
  end
  
  def invitation_token=(token)
    self.invitation = Invitation.find_by_token(token)
  end
 
 def self.get_csv(options = {})
    columns=["name","email","homepage","contact"]
  CSV.generate(options) do |csv|
    csv << ["Name","E-mail","Homepage","Contact"]
    all.each do |user|  
      csv << user.attributes.values_at(*columns)
    end
  end
end

def should_validate_user
  !project_user
end

def should_not_validate_user
  project_user
end

def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
end
  
  def self.authenticate(email, submitted_password)
    user=find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt==cookie_salt) ? user : nil 
  end
  
  def member_of(project)
    self.memberships.where(:project_id=>project.id).first
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
   
private
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password=encrypt(password)
  end
  
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
   
   def secure_hash(string)
     Digest::SHA2.hexdigest(string)
   end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  #before_filter :admin_user , :only => :destroy, :dependent => :destroy
  before_filter :authorize
  delegate :allow?, to: :current_permission
  helper_method :allow?
  
  def new
    @title = "Sign up"
    @user=User.new(:invitation_token => params[:invitation_token])
    @user.email=@user.invitation.recipient_email if @user.invitation
    #Creating a project user if unregistered user needs to be created. 
      1.times do
        membership = @user.memberships.build
        1.times { membership.designations.build } unless params[:project_user].nil?
      end 
  end

  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
    #Returning all users assigned to the currently open project, using the Memberships model as the join
    #The results may contain duplicates as a user may have multiple entries in memberships depending on his roles
    #and responsibilities and so we return unique memberships.
    @proj_users = current_project.users unless current_project.nil?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proj_users }
      format.csv { send_data @proj_users.get_csv }
      format.xls 
      format.pdf {
        pdf=UserPdf.new(@proj_users,view_context)
        send_data pdf.render, filename: "users.pdf",
                              type: "application/pdf",
                              disposition: "inline"
                              } 
    end 
  end
  
  def show
    @user=User.find(params[:id])
    @title=@user.name
  end
  
  def create
    #Creating/Registering new user
    if params[:project_user].nil?
     @user = User.new(params[:user])
     
     if @user.save 
          signin @user
          cookies.delete(:open_project) 
        flash[:success] = "Welcome to the digital library project management tool. Start by creating a new digital library project"
        redirect_to @user
            
        else
          @title="Sign up"
          render 'new'
      end
     else
    #Creating Project user(Drop-down/new one)
    #if no user is chosen from drop-down
    if params[:user][:id].empty?
      redirect_to :back
      flash[:notice]="Enter user information before saving"
      #puts "bad"
      #sleep(5)
    end
    #Put a conditional ? : statement 
    if params[:project_user]     
          @user=User.find_by_id(params[:user][:id])
          @user.project_user=true
          
          @user.update_attributes params[:user]
          @user.save

         # @Projectuser= Membership.where(:project_id=>current_project.id, :user_id=>@user.id)
         # @Projectuser.first.level=1
          
          redirect_to users_path
      end 
  end#big if
end
  
 def edit
   @user = User.find(params[:id])
   @title = "Edit user"
 end
 

  def update
    @user = User.find(params[:id])
     @user.update_attributes(params[:user])
     respond_with @user

  end
  
  def remove
   @membership=User.find_by_id(params[:userid]).member_of(current_project)
   @membership.delete
   @membership.designations.delete_all
   redirect_to(projects_path)
  end
 
 def admin_user
   redirect_to(root_path) unless current_user.admin?
 end

 private
 def authenticate
   deny_access unless signed_in?
 end
end

  #Useless
  def rake_users
     @errors=[]
    if params[:file].nil?
      @errors<<"Specify an XML file to import"
      flash[:notice]=@errors
    else
      xsd = Nokogiri::XML::Schema(File.read("project-users.xsd"))
      doc = Nokogiri::XML(params[:file].read)
      xsd.validate(doc).each do |error|
          @errors<<error
      end
  
      if !@errors.empty?
        flash[:notice] = @errors
      end

      if !params[:file].nil? && @errors.empty?
        doc.xpath("//user").each do |user|
          name = user.xpath("name").text
          email = user.xpath("email").text
          homepage = user.xpath("homepage").text
          contact =  user.xpath("contact").text
          
          @user=User.new(:name=>name,:email=>email,:homepage=>homepage,:contact=>contact)
          @user.project_user=true
          if @user.save
            flash[:notice]="Users created"
          else
            flash[:notice]=@user.errors 
          end
          end
      end
    end
    
    redirect_to :back
  end
  

app/helpers/users_helper.rb
module UsersHelper

  def current_project_users
    current_project.users do |d|
       return Array[d]    
    end
  end
  def display_users(users)
           ret = '<ul CLASS ="mktree">'
     for category in categories
       if category.parent_id == nil
      ret += "<li>"
      ret += link_to category.name, category
      ret += "&nbsp;&nbsp;"
      

      if category.children.size >0 && category_owner_children(category) == 1
       ret += find_all_subcategories(category)
       end
      ret += "</li>"
    
       end
       
     end
     ret += "</ul>"
     ret.html_safe
    end
end

app/views/users/_designation_edit.html.erb
<%admin_levels= { 1=> "Non-Admin", 0=> "Admin" }%>
		<%= render 'shared/error_messages', :object => f.object%>
		
		<div class="field">
			<%=f.fields_for :memberships, @user.member_of(current_project) do |builder|%>
				<%= builder.label :level%>
				<%= builder.collection_select(:level,admin_levels, :first, :last)%>
			<%end%>
		</div>
		<div class="field">	
				<%=f.fields_for :memberships, @user.member_of(current_project)  do |builder|%>
				<%= builder.hidden_field :project_id,:value=>current_project.id%>
				<%= builder.fields_for :designations do |b|%>
					<%= render 'designation_fields', :f=>b%>
					<%= link_to_add_fields "Add designation",builder,:designations%>
				<%end%>
				<%end%>
		</div>

app/views/users/_form.html.erb
<div class="outer_div">
	<div class="bigger_inner_div clearfix">
		<%= form_for @user,:validate=>true do |f|%>
		<%= render 'shared/error_messages', :object => f.object%>
		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :homepage %>
			<%= f.text_field :homepage %>
		</div>
		<div class="field">
			<%= f.label :contact %>
			<%= f.text_field :contact %>
		</div>
		<b><u>Change your password:</u></b>
		<div class="field">
			<%= f.label :password %>
			<%= f.password_field :password %>
		</div>
		<div class="field">
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
		</div>
		
		<div class="actions">
			<%= f.submit "Save", :class=>"custom_button round"%>
		</div>
		<%end%>
	</div>
</div>

app/views/users/_profile_edit.html.erb
	<%= render 'shared/error_messages', :object => f.object%>
		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :homepage %>
			<%= f.text_field :homepage %>
		</div>
		<div class="field">
			<%= f.label "Contact number" %>
			<%= f.text_field :contact %>
		</div>
		<b><u>Change your password:</u></b>
		<div class="field">
			<%= f.label :password %>
			<%= f.password_field :password %>
		</div>
		<div class="field">
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
		</div>

app/views/users/_project_user.html.erb
<%admin_levels= { 1=> "Non-Admin", 0=> "Admin" }%>
<h4 style="text-align: center;margin-top: 10px;">Add user to <%=current_project.name%> </h4>
<div class="hint" style="text-align: center;">Include users in the project. Assign roles to users and describe their responsibilities. 
	A user can have many roles</div>
<div class="outer_div">
	<div class="bigger_inner_div">
		<%= form_for @user, :url => {:controller => "users", :action => "create"},:validate=>true do |f| %>
			<p class="fields">
			<%=f.label "User"%>
			<%= collection_select(:user,:id, User.find(:all,:conditions=>['id not in (?)', current_project.users.map(&:id)]), :id, :name,{:prompt=>""} ) if !current_project.nil? && !current_project.users.nil?%>
			<%=hidden_field_tag :project_user, true%>
			</p>
			<div class="field">
				<%=f.fields_for :memberships do |builder|%>
				<%= builder.hidden_field :project_id,:value=>current_project.id%>
				<%= builder.label :level%>
				<%= builder.collection_select(:level,admin_levels, :first, :last)%>
				<%= builder.fields_for :designations do |b|%>
					<%= render 'designation_fields', :f=>b%>
					<%= link_to_add_fields "Add designation",builder,:designations%>
				<%end%>
				<%end%>
			</div>
			<div class="actions">
				<%= f.submit "Add user",:class=>"custom_better_button"%>
			</div>
		<%end%>		
		</div>
	</div>
</div>

app/views/users/_project_user_old.html.erb
<h4 style="text-align: center;margin-top: 10px;">Add user to <%=current_project.name%> </h4>
<div class="hint" style="text-align: center;">Include users in the project or create a new unregsitered user. Assign roles and responsibilities arising from those roles.
	A user can have many roles</div>
<div class="outer_div">
<div class="bigger_inner_div">
	<%= field_set_tag nil, :class => 'field' do %>
	<p> Select XML file to import users</p>
	<%= form_tag('/rake_users', :method=>'post', :multipart => true,:class=>"clearfix") do%>
	<%=file_field_tag :file%>
	<%= submit_tag "Submit",:class=>"custom_better_button"%>
	<%end%>
	<%end%>
	<div id="project_user_accordion">
		<h3>Add existing user</h3>
	<div>
	<%= form_for @user, :url => {:controller => "users", :action => "create"},:validate=>true do |f| %>
		<p class="fields">
		Add existing user
		<%= collection_select(:user,:id, User.find(:all,:conditions=>['id not in (?)', current_project.users.map(&:id)]), :id, :name, {} ) if !current_project.nil? && !current_project.users.nil?%>
		<%=hidden_field_tag :project_user, true%>
		</p>
		<div class="field">
			<%=f.fields_for :delegations do |builder|%>
			<%= render 'delegation_fields', :f=>builder%>
			<%= link_to_add_fields "Add delegation",f,:delegations%>
			<%end%>
		</div>
		<div class="actions">
			<%= f.submit "Create",:class=>"custom_better_button"%>
		</div>
	<%end%>		
	</div>
	<h3>Add new user</h3>
<%= form_for @user, :url => {:controller => "users", :action => "create"},:validate=>true  do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@user.errors.count, "error") %> prohibited this project from being saved:</h2>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<%=hidden_field_tag :project_user, true%>
<div class="field">
	<%= f.label "User name"%> <!--Change it depending on whether adding a new user of assigning an existing user-->
	<%= f.text_field :name%> <!--<%=collection_select(:user,:id, User.all, :id, :name, {} )%>-->
</div>
<div class="field">
	<%= f.label "User email"%> <!--Change it depending on whether adding a new user of assigning an existing user-->
	<%= f.text_field :email%> <!--<%=collection_select(:user,:id, User.all, :id, :name, {} )%>-->
</div>
<div class="field">
	<%= f.label "homepage"%> <!--Change it depending on whether adding a new user of assigning an existing user-->
	<%= f.text_field :homepage%> <!--<%=collection_select(:user,:id, User.all, :id, :name, {} )%>-->
</div>
<div class="field">
	<%= f.label "Contact number"%> <!--Change it depending on whether adding a new user of assigning an existing user-->
	<%= f.text_field :contact%> <!--<%=collection_select(:user,:id, User.all, :id, :name, {} )%>-->
</div>
<div class="field">
	<%=f.fields_for :delegations do |builder|%>
	<%= render 'delegation_fields', :f=>builder%>
	<%= link_to_add_fields "Add delegation",f,:delegations%>
	<%end%>
</div>
<div class="actions">
	<%= f.submit "Create",:class=>"custom_better_button"%>
</div>
<% end %>
</div></div>

app/views/users/_show_delegation_fields.html.erb
<p class="fields">
	Role: <%= f.role %>
	<br/>
	Responsibilities:<%= f.responsibility%>
	<%= link_to_remove_fields "Remove delegation", f %>
</p>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
	<!--<% if current_user.admin?%>-->
	<%= link_to "| delete", user, :method => :delete, :confirm => "You sure?", :title => "Delete #{user.name}" %>
	<!--<%end%>-->
</li>

app/views/users/_user_invitation.html.erb
<div id="user_bar">
<% if !current_user.nil? %>
  <p>Welcome <%= current_user.name %> (<%= link_to 'log-out', signout_path %>)</p>
  <%=link_to "Send invitation", new_invitation_path%>
<% else %>
  <p>If you have an account, <%= link_to "Log-in", signin_path %></p>
<% end %>
</div>

app/views/users/_users_sidemenu.html.erb
<%if !current_project.nil?%>
	<div>People grouped by role <%=image_tag("group.png", :alt=>"People")%></div>
	<%current_project.memberships.collect{|m|m.designations}%>
	<%@uniq_designations=current_project.designations.uniq_by(&:role)%>
	<%@uniq_designations.delete_if{|x| x.role.blank?}%>
	<%if !@uniq_designations.nil?%>
	<div id="menu">       
	 <ul class="navmenu">	
	 <%@uniq_designations.each do |r|%>
	   <li>
	   	<div class="menutop">
	   		<a href="#">
	   			<%=r.role%>
	   		</a>
	   		<div class="toggle">+</div>
	   	</div>
	     <ul class="submenu">
	     	<%@designations=current_project.designations.find(:all, :conditions=>["role=?",r.role])%>
			<%@designations.each do |d|%>
				<%@members=Membership.find(:all, :conditions=>["id=?",d.membership_id])%>
				<%@members.each do |m|%>
					<%@u=User.find(:all, :conditions=>["id=?",m.user_id])%>
						<%@u.each do |u|%>
				       		<li><a href="#"><%=u.name%></a></li>
				       <%end%>
				<%end%>
	       <%end%>
	     </ul>
	    </li>
	   <%end%>
	 </ul>
	 </div>
	 <%else%>
	 <p id="empty_entity">No roles assigned to users in the project <%=link_to current_project.name,current_project%></p><br/>
	 <p class="add_link">
	 	<%= link_to "Add user to project",new_user_path(:project_user=>"true")%>
	 </p>
	<%end%>
	<%else%>
	 	 <p id="empty_entity">Currently not viewing any project </p>
	 	 <p class="add_link"><%= link_to "Create a new DL project",new_project_path%></p>
  <%end%>
  <%if !current_project.nil?%>
	 <p class="add_link">
	 	<% if current_user.member_of(current_project) && (current_user.member_of(current_project)).admin?%>
	 	<%= link_to "Add user to project",new_user_path(:project_user=>"true")%></p>
	 	<%end%>
	 <%end%>

app/views/users/index.html.erb
<%content_for :side do%>
	<%if !current_project.nil?%>
		<%= render 'users_sidemenu'%>
	<%end%>
<%end%>
<%content_for :main do%> 
	
	<%if !current_project.nil?%>
		<h4 style="text-align: center;margin-top: 10px">People involved in <%=link_to "#{current_project.name}",current_project%> </h4>
		<%=render 'user_invitation'%>
		
			<ul class="users">
			<%= render 'users' %>
		</ul>
	<%else%>
		 <p id="empty_entity">Currently not viewing any project </p>
	 	 <p class="add_link"><%= link_to "Add new project",new_project_path%>&nbsp;&nbsp;<!--<%=link_to image_tag("add.png", :alt=>"Add project"),new_project_path%>--></p>

	<%end%>


<!--
<h2>Project users in this project</h2>
<%if !@proj_users.nil?%>
<ul>
	<%@proj_users.each do |r|%>
	<li>
		<%= r[:name]%>
	</li>
	<%end%>
</ul>
<%end%>
</div-->
<%end%> 

app/views/users/new.html.erb
<%if params[:project_user].nil?%>
<link rel="icon" type="image/ico" href="assets/add.png">
</head>
<body>
	<div class="wrapper">
		<div class="google-header-bar">
			<div class="header content clearfix">
			</div>
		</div>
		<div class="main content clearfix">
			<div class="sign-in">
				<div class="signin-box">
					<h2>Sign up</h2>
					<%= form_for @user,:validate=>true do |f|%>
					<%= f.hidden_field :invitation_token %>
					<div class="field email-div">
						<%= f.label :name,:class=>"email-label" %>
						<%= f.text_field :name ,:id=>"Email"%>
					</div>
					<div class="field email-div">
						<%= f.label :email,:class=>"email-label" %>
						<%= f.text_field :email ,:id=>"Email"%>
					</div>
					<div class="field passwd-div">
						<%= f.label :password,:class=>"passwd-label" %>
						<%= f.password_field :password %>
					</div>
					<div class="field passwd-div">
						<%= f.label :password_confirmation,:class=>"passwd-label" %>
						<%= f.password_field :password_confirmation %>
					</div>
					<div class="signup_button">
						<%= f.submit "Register",:id=>"signIn",:class=>"g-button g-button-submit"%>
					</div>
					
					<%end%>
				</div>
			</div>
			<div class="product-info mail">
				<div class="product-headers">
					<h1 class="redtext">Digital Library Development Management Tool</h1>
					<h2>Structuring the world of digital library management (DLM)</h2>
				</div>
				<p>
					Building a digital library is no easy task. Managing development is made easier and more streamlined
					using the DLM Tool. It supports project management, yet is tailored for digital librarians. 
				</p>
				<ul class="features">
					<li>
						<%=image_tag("group.png",:alt=>"Collaboration")%>
						<%=image_tag("world.png",:alt=>"Collaboration")%>
						<p class="title redtext">
							Collaborate
						</p>
						<p>
							Share tasks, projects and calendars with people located anywhere in the world.
						</p>
					</li>
					<li>
						<%=image_tag("timeline_marker.png",:alt=>"Timeline")%>
						<%=image_tag("table.png",:alt=>"Timeline")%>
						<p class="title redtext">
							Fluid view
						</p>
						<p>
							Make and modify timelines, tables and lists of project phases
						</p>
					</li>
					<li>
						<%=image_tag("lock.png",:alt=>"protected access")%>
						<%=image_tag("page_white_zip.png",:alt=>"Protected access")%>
						<p class="title redtext">
							Protected access
						</p>
						<p>
							Create private projects made vieweable only for select people
						</p>
					</li>
				</ul>
				<ul class="mail-links">
					<li></li>
				</ul>
				<div class="mailPromo"></div>
		</div>

<%else%>
	<%content_for :side do%>
		<%if !current_project.nil?%>
			<%= render 'users_sidemenu'%>
		<%end%>
	<%end%>

	<%content_for :main do%>
		<%= render 'project_user'%>
	<%end%>
<%end%>
<!--<div class="grid_16">
	<div class="grid_12 layout alpha" >
		"Text for welcome"
	</div>
	<div class="grid_4 omega layout" id="right_display" >
		<h2>Sign in</h2>
		<%= form_for(:session, :url => sessions_path) do |f|%>
		<div class="field">
			<%= f.label :email %>
			<br/>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password %>
			<br/>
			<%= f.password_field :password %>
		</div>
		<div class="signup_button">
			<%= f.submit "Sign in",:id=>"signup_button",:class=>"round"%>
		</div>
		<%end%>
		<p>
			New user? <%= link_to "Sign up now!", signup_path%>
		</p>
	</div>
-->

app/views/users/show.html.erb
<%content_for :side do%>
<%if !current_project.nil?%>
	<%= render 'users_sidemenu'%>
<%end%>
<%end%>
<%content_for :main do%>
<div class="outer_div">
	<div class="bigger_inner_div clearfix">
		
		<%if current_project && @user.member_of(current_project) && (@user.member_of(current_project)).admin?%>
			You are an administrator on the current project
		<%end%>
		<!--<p> <%=link_to "Change Password",edit_password_reset_path(@user) %></p>-->
		<p>
			<b>Name:</b>
			<%= best_in_place @user, :name %>
		</p>
		<p>
			<b>Email:</b>
			<%= best_in_place @user, :email %>
		</p>
		<p>
			<% if !@user.homepage.nil?%>
			<b>Homepage</b>
			<%= link_to @user.homepage, url_with_protocol(@user.homepage)%>
			<%end%>
		</p>
		<p>
			<% if !@user.contact.nil?%>
			<b>Contact Number:</b>
			<%= best_in_place @user, :contact %>
			<%end%>
		</p>
		<p>
		 <table>
		 	<%if current_project%>
				<%@user.memberships.where(:project_id=>current_project.id).each do |m|%>
					<%m.designations.each do |d|%>
					<%if d.role%>
						<tr><td style="vertical-align:top"><b>Role:</b></td><td><%= d.role%></td></tr>
						<tr><td colspan="2" style="vertical-align:top"><b>Responsibilities</b><br/><%= d.responsibility%></td></tr>
					<%else%>
						      You have not been assigned a role yet. Click on the "Edit" button to add a role.
						<%end%>
					<%end%>
				<%end%>
			<%end%>
		 </table>
		</p>
		<!--Dont display edit button if user does not have permission. Combined current_permission and authorize methods in applicaion_controller-->
		<%if Permission.new(current_membership).allow?("user", "edit",current_user, current_project,params[:id])%>
			<%= link_to 'Edit', edit_user_path(@user),:class=>"custom_better_button round" %> 
		<%end%>
		<%= link_to 'Back', users_path,:class=>"custom_better_button round righty" %>
	</div>
</div>
<%end%> 