config/routes.rb
SampleApp::Application.routes.draw do
  resources :invitations
  resources :password_resets
  resources :default_policies

  resources :meta do 
    resources :resources
  end

  resources :resources

  resources :phases

  resources :policies

  resources :events
  match '/generate_stream'=>'meta#generate_stream'
  match '/generate_structure'=>'meta#generate_structure'
  match '/generate_scenario'=>'meta#generate_scenario'
  match '/generate_space'=>'meta#generate_space'
  match '/generate_society'=>'meta#generate_society'
  match '/rake_tasks'=>'tasks#rake_tasks'
  match '/rake_phases'=>'phases#rake_phases'
  match '/rake_users'=>'users#rake_users'
  match "phases/savesort" => 'phases#savesort'
  match "shippings_logs/recent"=> 'shipping_logs#recent'
  match '/articles(/:year(/:month))' => 'articles#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'events#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/tasks/calendar(/:year(/:month))' => 'tasks#view_calendar', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  match '/tasks/rake_tasks', :to => 'tasks#rake_tasks'
  
  resources :tasks do 
    resources :resources
  end
  get "sessions/new"

  resources :users 
    match '/users/:id/' => 'users#update', :format =>:json, :via => :put
  resources :sessions, :only => [:new,:create,:destroy]
  
  match "/projects/withdraw", :controller => 'projects', :action => 'withdraw'
   match "/defaultphases/:id", :to=>'defaultphases#show'
   match "/soc_del", :to=>'meta#soc_del'
   match "/struc_del", :to=>'meta#struc_del'
  
  match "/tasks/index.js", :controller => 'tasks', :action => 'index', :format => :js
  get "users/new"
  match "/phases/make", :to=>'phases#make', :via => :post

  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signup/:invitation_token', :to=>'users#new'
  match '/signin', :to => 'pages#home'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  
  resources :projects do 
    resources :resources
  end
  

  match '/projects/new_user', :to=>'projects#new_user'
  match '/users/remove', :to=>'users#remove'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
  belongs_to :project 
  
    def self.get_csv(options = {})
    columns=["name","content","start_at","end_at"]
  CSV.generate(options) do |csv|
    csv << ["Event name", "Description","Start Date", "End date"]
    all.each do |event|
      csv << event.attributes.values_at(*columns)
    end
  end
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_login
  # GET /events
  # GET /events.json
  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i
    @shown_month = Date.civil(@year, @month)
    @events=current_project.events unless current_project.nil?
    
    #Displaying only current project's events
    if !current_project.nil?
      @event_strips = current_project.events.event_strips_for_month(@shown_month) if !current_project.nil?
    end 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
      format.csv { send_data @events.get_csv }
      format.xls
      format.pdf {
        pdf = EventPdf.new(current_project.events,view_context) 
        send_data  pdf.render, filename: "events.pdf",
                              type: "application/pdf",
                              disposition: "inline"
                              } 
    end 
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event } 
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event=Event.new  
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project.events }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.create(params[:event])
    respond_to do |format|
      if @event.save
        current_project.events<<@event
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
  private
   def require_login
    deny_access unless signed_in?    
  end 
end

app/helpers/events_helper.rb
module EventsHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
  
    def current_project_events
     current_project.events.each do |d|
       return Array[d]
       end
  end
  
end

app/views/events/_events_sidemenu.html.erb
<br/><h3><%= link_to "Events",events_path%> </h3>

<div id="treeViewDiv_events"></div>
<br/>
<%if !current_project.nil?%>
<p class="add_link"> <%=link_to "Add an event/meeting",new_event_path%>&nbsp;&nbsp; <!--<%=link_to image_tag("add.png", :alt=>"Add events"),new_event_path%>--></p>
<%else%>
<p class="add_link"><%= link_to "Create a new DL project",new_project_path%>&nbsp;&nbsp;<!--<%=link_to image_tag("add.png", :alt=>"Add project"),new_project_path%>--></p>
<%end%>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="outer_div">
	<div class="bigger_inner_div clearfix">
	  <div class="field">
	    <%= f.label :name %><span class="hint"> Enter the name of the event</span>
	    <%= field_set_tag nil, :class => 'field' do %>
	    <%= f.text_field :name %>
	    <%end%>
	  </div>
	  <div class="field">
	    <%= f.label "Description" %><span class="hint"> Enter a brief description of the event</span>
	    <%= field_set_tag nil, :class => 'field' do %>
	    <%= f.text_area :content %>
	    <%end%>
	  </div>
	  <div class="field">
	    <%= f.label :start_at %><span class="hint"> Enter the tentative start date of the event</span>
	    <%= field_set_tag nil, :class => 'field' do %>
	    <%= f.text_field :start_at %>
	    <%end%>
	  </div>
	  <div class="field">
	    <%= f.label :end_at %><span class="hint"> Enter the tentative end date of the event</span>
	    <%= field_set_tag nil, :class => 'field' do %>
	    <%= f.text_field :end_at %>
	    <%end%>
	  </div>
	  <div class="actions">
	    <%= f.submit "Save",:class=>"custom_better_button righty" %>
	    <%= link_to 'Back', events_path,:class=>"custom_better_button righty" %>
	  </div>
<% end %>
</div></div>

app/views/events/edit.html.erb
<%content_for :side do%>
	<%= render 'events_sidemenu'%>
<%end%>
<%content_for :main do%>
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>
<%end%>

app/views/events/index.html.erb
<%content_for :side do%>
	<%= render 'events_sidemenu'%>
<%end%>
<%content_for :main do%>
<br/>
<%if !current_project.nil?%>
<h2>Calendar</h2>
	<%if current_project.nil?%>
		<%=empty_display("projects")%>
	<%elsif current_project_events.empty?%>
		<%=empty_display("events")%>
	<%end%>
	<p>
  Download:
  <%= link_to "CSV", events_path(format: "csv") %> 
  <%= link_to "Printable PDF", events_path(format: "pdf"), :class=>"righty"%>
</p>

	<%= raw(event_calendar) %>
<%else%>
<div class="outer_div">
	<div class="bigger_inner_div clearfix">
		<h4 style="text-align: center;">Create/open a new project and add events to view them in calendar format.</h4>
	</div>
</div>
<%end%>
</div>
<%end%>

app/views/events/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Start date</Data></Cell>
        <Cell><Data ss:Type="String">End date</Data></Cell>
      </Row>
    <% @events.each do |event| %>
      <Row>
        <Cell><Data ss:Type="String"><%= event.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.start_at %></Data></Cell>
        <Cell><Data ss:Type="String"><%= event.end_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/events/new.html.erb
<%content_for :side do%>
	<%= render 'events_sidemenu'%>
<%end%>
<%content_for :main do%>
<h3 style="text-align: center;">New event</h3>

<%= render 'form' %>


</div>
<%end%>

app/views/events/show.html.erb
<%content_for :side do%>
<%= render 'events_sidemenu'%>
<%end%>
<%content_for :main do%>
<div class="outer_div">
	<div class="inner_div clearfix">
		<p id="notice">
			<%= notice %>
		</p>
		<p>
			<b><%= image_tag("star.png",:alt=>"Event")%>&nbsp;Name:</b>
			<%= best_in_place @event,:name %>
		</p>
		<p>
			<b><%= image_tag("date_next.png",:alt=>"Start date")%>&nbsp;Start at:</b>
			<%= best_in_place @event,:start_at %>
		</p>
		<p>
			<b><%= image_tag("date_previous.png",:alt=>"End date")%>&nbsp;End date:</b>
			<%= best_in_place @event,:end_at %>
		</p>
		<!--<%= link_to 'Edit', edit_event_path(@event) %> |-->
		<%= link_to 'Back', events_path,:class=>"custom_button round righty" %>
	</div>
</div>
<%end%> 

app/views/events/spare_index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.date %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>