config/routes.rb
SampleApp::Application.routes.draw do
  resources :invitations
  resources :password_resets
  resources :default_policies

  resources :meta do 
    resources :resources
  end

  resources :resources

  resources :phases

  resources :policies

  resources :events
  match '/generate_stream'=>'meta#generate_stream'
  match '/generate_structure'=>'meta#generate_structure'
  match '/generate_scenario'=>'meta#generate_scenario'
  match '/generate_space'=>'meta#generate_space'
  match '/generate_society'=>'meta#generate_society'
  match '/rake_tasks'=>'tasks#rake_tasks'
  match '/rake_phases'=>'phases#rake_phases'
  match '/rake_users'=>'users#rake_users'
  match "phases/savesort" => 'phases#savesort'
  match "shippings_logs/recent"=> 'shipping_logs#recent'
  match '/articles(/:year(/:month))' => 'articles#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/events(/:year(/:month))' => 'events#index', :as => :articles, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  match '/tasks/calendar(/:year(/:month))' => 'tasks#view_calendar', :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  match '/tasks/rake_tasks', :to => 'tasks#rake_tasks'
  
  resources :tasks do 
    resources :resources
  end
  get "sessions/new"

  resources :users 
    match '/users/:id/' => 'users#update', :format =>:json, :via => :put
  resources :sessions, :only => [:new,:create,:destroy]
  
  match "/projects/withdraw", :controller => 'projects', :action => 'withdraw'
   match "/defaultphases/:id", :to=>'defaultphases#show'
   match "/soc_del", :to=>'meta#soc_del'
   match "/struc_del", :to=>'meta#struc_del'
  
  match "/tasks/index.js", :controller => 'tasks', :action => 'index', :format => :js
  get "users/new"
  match "/phases/make", :to=>'phases#make', :via => :post

  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signup/:invitation_token', :to=>'users#new'
  match '/signin', :to => 'pages#home'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  
  resources :projects do 
    resources :resources
  end
  

  match '/projects/new_user', :to=>'projects#new_user'
  match '/users/remove', :to=>'users#remove'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_resources.html.erb

<!--<%= form_for [@resourceable, Resource.new] do |f| %>
  <ol class="formList">
	<%=f.file_field :file%>
	<%= f.submit "Rake tasks", :controller => :tasks, 
                           :action => 'rake_tasks',:class=>"custom_better_button"%>
  </ol>
<% end %>-->
<div class="outer_div">
	<div class="bigger_inner_div">
<h4 style="text-align: center;margin-top: 10px;">Upload resources for the project</h4><br/>
<p> Select files to add to the project. Uploaded files are listed below. Click on a file to download it. </p>
<%=form_for [@resourceable, Resource.new], :html => { :multipart => true, :id => "fileupload"  } do |f| %>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="span7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Add files...</span>
                    <%= f.file_field :resourcer %>
                </span>&nbsp;
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="icon-trash icon-white"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
            </div>
            <div class="span5">
                <!-- The global progress bar -->
                <div class="progress progress-success progress-striped active fade">
                    <div class="bar" style="width:0%;"></div>
                </div>
            </div>
        </div>
        <!-- The loading indicator is shown during image processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
        </table>
    <% end %>
   </div>
  </div>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<!--<h1>Listing resources</h1>-->

<ul id="resources">
  <% @resources.each do |resource| %>
    <li><%= resource.content %></li>
<%end%>
</ul>
<%=render 'resources'%>

<!--<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.name %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>-->

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resource.name %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>